"""All ORM models. Importing this module registers every table on ``Base``."""

from app.db.base import Base
from app.db.models.catalog import (
    Category,
    InventoryAdjustment,
    InventoryItem,
    InventoryReservation,
    Product,
    ProductMedia,
)
from app.db.models.order import (
    Coupon,
    CouponUsage,
    Delivery,
    LedgerEntry,
    Order,
    OrderItem,
    Refund,
)
from app.db.models.payment import (
    BlockchainTransaction,
    PaymentAttempt,
    PaymentConsumption,
    PaymentIntent,
    PaymentMethod,
    PaymentProvider,
    ProviderTransaction,
    ReconciliationRecord,
    VerificationAttempt,
)
from app.db.models.reseller import (
    ApiKey,
    IdempotencyRecord,
    ResellerAccount,
    WebhookDelivery,
    WebhookEndpoint,
)
from app.db.models.support import (
    AuditLog,
    Broadcast,
    SupportMessage,
    SupportTicket,
    SystemSetting,
)
from app.db.models.user import (
    Notification,
    Permission,
    Referral,
    RestockSubscription,
    Role,
    User,
    role_permissions,
    user_roles,
)

__all__ = [
    "ApiKey",
    "AuditLog",
    "Base",
    "BlockchainTransaction",
    "Broadcast",
    "Category",
    "Coupon",
    "CouponUsage",
    "Delivery",
    "IdempotencyRecord",
    "InventoryAdjustment",
    "InventoryItem",
    "InventoryReservation",
    "LedgerEntry",
    "Notification",
    "Order",
    "OrderItem",
    "PaymentAttempt",
    "PaymentConsumption",
    "PaymentIntent",
    "PaymentMethod",
    "PaymentProvider",
    "Permission",
    "Product",
    "ProductMedia",
    "ProviderTransaction",
    "ReconciliationRecord",
    "Referral",
    "Refund",
    "ResellerAccount",
    "RestockSubscription",
    "Role",
    "SupportMessage",
    "SupportTicket",
    "SystemSetting",
    "User",
    "VerificationAttempt",
    "WebhookDelivery",
    "WebhookEndpoint",
    "role_permissions",
    "user_roles",
]
