"""initial schema

Revision ID: a0bcf6dd96f1
Revises: 
Create Date: 2026-09-05 01:52:00.641715
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# Custom column types (GUID, JSONB, Money) live in the application's declarative
# base, so migrations import it rather than duplicating the definitions.
import app.db.base


revision: str = 'a0bcf6dd96f1'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blockchain_transactions',
    sa.Column('id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('network', sa.Enum('TRC20', 'BEP20', 'ERC20', 'TON', 'SOL', 'AVAXC', 'ARBITRUM', 'POLYGON', 'BTC', 'LTC', 'EXCHANGE_INTERNAL', name='networkcode', native_enum=False, length=24), nullable=False),
    sa.Column('txid', sa.String(length=160), nullable=False),
    sa.Column('log_index', sa.Integer(), nullable=False),
    sa.Column('asset', sa.String(length=16), nullable=False),
    sa.Column('token_contract', sa.String(length=128), nullable=True),
    sa.Column('from_address', sa.String(length=255), nullable=True),
    sa.Column('to_address', sa.String(length=255), nullable=False),
    sa.Column('to_address_normalized', sa.String(length=255), nullable=False),
    sa.Column('amount_units', sa.Numeric(precision=78, scale=0, asdecimal=False), nullable=False),
    sa.Column('amount', sa.Numeric(precision=30, scale=8), nullable=False),
    sa.Column('decimals', sa.Integer(), nullable=False),
    sa.Column('memo', sa.String(length=160), nullable=True),
    sa.Column('block_number', sa.BigInteger(), nullable=True),
    sa.Column('block_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmations', sa.Integer(), nullable=False),
    sa.Column('is_successful', sa.Boolean(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_payload', app.db.base.JSONB(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blockchain_transactions')),
    sa.UniqueConstraint('network', 'txid', 'log_index', name='uq_blockchain_transactions_network')
    )
    op.create_index(op.f('ix_blockchain_transactions_created_at'), 'blockchain_transactions', ['created_at'], unique=False)
    op.create_index('ix_blockchain_transactions_receiver', 'blockchain_transactions', ['network', 'to_address_normalized'], unique=False)
    op.create_table('categories',
    sa.Column('id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name_en', sa.String(length=128), nullable=False),
    sa.Column('name_bn', sa.String(length=128), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('emoji', sa.String(length=8), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_priority', sa.Integer(), nullable=False),
    sa.Column('parent_id', app.db.base.GUID(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], name=op.f('fk_categories_parent_id_categories'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories')),
    sa.UniqueConstraint('slug', name='uq_categories_slug')
    )
    op.create_index(op.f('ix_categories_created_at'), 'categories', ['created_at'], unique=False)
    op.create_index(op.f('ix_categories_is_active'), 'categories', ['is_active'], unique=False)
    op.create_table('idempotency_records',
    sa.Column('id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('scope', sa.String(length=96), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('request_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('response_status', sa.Integer(), nullable=False),
    sa.Column('response_body', app.db.base.JSONB(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_idempotency_records')),
    sa.UniqueConstraint('scope', 'key', name='uq_idempotency_records_scope')
    )
    op.create_index(op.f('ix_idempotency_records_created_at'), 'idempotency_records', ['created_at'], unique=False)
    op.create_index(op.f('ix_idempotency_records_expires_at'), 'idempotency_records', ['expires_at'], unique=False)
    op.create_table('payment_providers',
    sa.Column('id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('code', sa.Enum('BINANCE', 'BINANCE_PAY', 'BYBIT', 'OKX', 'TRON', 'EVM', 'TON', 'SOLANA', 'UTXO', name='providercode', native_enum=False, length=24), nullable=False),
    sa.Column('kind', sa.Enum('EXCHANGE', 'BLOCKCHAIN', name='paymentproviderkind', native_enum=False, length=16), nullable=False),
    sa.Column('display_name', sa.String(length=64), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('encrypted_api_key', sa.Text(), nullable=True),
    sa.Column('encrypted_api_secret', sa.Text(), nullable=True),
    sa.Column('encrypted_passphrase', sa.Text(), nullable=True),
    sa.Column('api_key_hint', sa.String(length=16), nullable=True),
    sa.Column('account_identifier', sa.String(length=128), nullable=True),
    sa.Column('base_url', sa.String(length=255), nullable=True),
    sa.Column('config', app.db.base.JSONB(), nullable=False),
    sa.Column('health_status', sa.String(length=16), nullable=False),
    sa.Column('health_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('health_latency_ms', sa.Integer(), nullable=True),
    sa.Column('health_message', sa.String(length=255), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment_providers')),
    sa.UniqueConstraint('code', name='uq_payment_providers_code')
    )
    op.create_index(op.f('ix_payment_providers_created_at'), 'payment_providers', ['created_at'], unique=False)
    op.create_index(op.f('ix_payment_providers_is_enabled'), 'payment_providers', ['is_enabled'], unique=False)
    op.create_table('permissions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permissions')),
    sa.UniqueConstraint('code', name=op.f('uq_permissions_code'))
    )
    op.create_table('provider_transactions',
    sa.Column('id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('provider_code', sa.Enum('BINANCE', 'BINANCE_PAY', 'BYBIT', 'OKX', 'TRON', 'EVM', 'TON', 'SOLANA', 'UTXO', name='providercode', native_enum=False, length=24), nullable=False),
    sa.Column('external_id', sa.String(length=160), nullable=False),
    sa.Column('record_type', sa.String(length=32), nullable=False),
    sa.Column('asset', sa.String(length=16), nullable=False),
    sa.Column('network', sa.String(length=32), nullable=True),
    sa.Column('amount', sa.Numeric(precision=30, scale=8), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('txid', sa.String(length=160), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('counterparty', sa.String(length=160), nullable=True),
    sa.Column('reference', sa.String(length=160), nullable=True),
    sa.Column('confirmations', sa.Integer(), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_payload', app.db.base.JSONB(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_provider_transactions')),
    sa.UniqueConstraint('provider_code', 'external_id', name='uq_provider_transactions_provider_code')
    )
    op.create_index(op.f('ix_provider_transactions_created_at'), 'provider_transactions', ['created_at'], unique=False)
    op.create_index('ix_provider_transactions_lookup', 'provider_transactions', ['provider_code', 'asset', 'observed_at'], unique=False)
    op.create_index(op.f('ix_provider_transactions_reference'), 'provider_transactions', ['reference'], unique=False)
    op.create_index(op.f('ix_provider_transactions_txid'), 'provider_transactions', ['txid'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Enum('SUPER_ADMIN', 'ADMIN', 'PAYMENT_MANAGER', 'PRODUCT_MANAGER', 'SUPPORT_AGENT', 'ANALYST', 'RESELLER_MANAGER', name='rolename', native_enum=False, length=32), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('name', name=op.f('uq_roles_name'))
    )
    op.create_index(op.f('ix_roles_created_at'), 'roles', ['created_at'], unique=False)
    op.create_table('users',
    sa.Column('id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('first_name', sa.String(length=128), nullable=True),
    sa.Column('last_name', sa.String(length=128), nullable=True),
    sa.Column('language', sa.Enum('EN', 'BN', name='language', native_enum=False, length=8), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'RESTRICTED', 'BANNED', name='userstatus', native_enum=False, length=16), nullable=False),
    sa.Column('is_bot_blocked', sa.Boolean(), nullable=False),
    sa.Column('orders_count', sa.Integer(), nullable=False),
    sa.Column('completed_orders_count', sa.Integer(), nullable=False),
    sa.Column('total_spent', sa.Numeric(precision=30, scale=8), nullable=False),
    sa.Column('referral_code', sa.String(length=16), nullable=False),
    sa.Column('referred_by_id', app.db.base.GUID(length=36), nullable=True),
    sa.Column('referral_balance', sa.Numeric(precision=30, scale=8), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('risk_flags', app.db.base.JSONB(), nullable=False),
    sa.Column('internal_notes', sa.Text(), nullable=True),
    sa.Column('notifications_enabled', sa.Boolean(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['referred_by_id'], ['users.id'], name=op.f('fk_users_referred_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('referral_code', name=op.f('uq_users_referral_code'))
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_last_seen_at'), 'users', ['last_seen_at'], unique=False)
    op.create_index(op.f('ix_users_referred_by_id'), 'users', ['referred_by_id'], unique=False)
    op.create_index(op.f('ix_users_status'), 'users', ['status'], unique=False)
    op.create_index('ix_users_telegram_id', 'users', ['telegram_id'], unique=True)
    op.create_index('ix_users_username_lower', 'users', ['username'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('action', sa.Enum('LOGIN', 'PAYMENT_APPROVED', 'PAYMENT_REJECTED', 'PAYMENT_RECHECKED', 'ORDER_CANCELLED', 'ORDER_FORCED_DELIVERY', 'REFUND_CREATED', 'REFUND_COMPLETED', 'PRODUCT_CREATED', 'PRODUCT_UPDATED', 'PRODUCT_ARCHIVED', 'INVENTORY_ADDED', 'INVENTORY_ADJUSTED', 'COUPON_CREATED', 'COUPON_UPDATED', 'USER_RESTRICTED', 'USER_BANNED', 'RESELLER_APPROVED', 'RESELLER_SUSPENDED', 'API_KEY_CREATED', 'API_KEY_REVOKED', 'PROVIDER_CREDENTIALS_UPDATED', 'PROVIDER_TOGGLED', 'PAYMENT_METHOD_UPDATED', 'PAYMENT_ADDRESS_CHANGED', 'TOKEN_CONTRACT_CHANGED', 'SETTINGS_UPDATED', 'MAINTENANCE_TOGGLED', 'BROADCAST_SENT', 'ROLE_ASSIGNED', 'ROLE_REVOKED', name='auditaction', native_enum=False, length=48), nullable=False),
    sa.Column('actor_id', app.db.base.GUID(length=36), nullable=True),
    sa.Column('actor_label', sa.String(length=96), nullable=False),
    sa.Column('target_type', sa.String(length=48), nullable=True),
    sa.Column('target_id', sa.String(length=64), nullable=True),
    sa.Column('reason', sa.String(length=512), nullable=True),
    sa.Column('details', app.db.base.JSONB(), nullable=False),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_audit_logs_actor_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index('ix_audit_logs_action_created', 'audit_logs', ['action', 'created_at'], unique=False)
    op.create_index('ix_audit_logs_actor_created', 'audit_logs', ['actor_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index('ix_audit_logs_target', 'audit_logs', ['target_type', 'target_id'], unique=False)
    op.create_table('broadcasts',
    sa.Column('id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('created_by_id', app.db.base.GUID(length=36), nullable=True),
    sa.Column('audience', sa.Enum('ALL', 'ACTIVE', 'CUSTOMERS', 'RESELLERS', 'LANGUAGE', name='broadcastaudience', native_enum=False, length=16), nullable=False),
    sa.Column('audience_filter', app.db.base.JSONB(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'QUEUED', 'SENDING', 'COMPLETED', 'CANCELLED', name='broadcaststatus', native_enum=False, length=16), nullable=False),
    sa.Column('total_recipients', sa.Integer(), nullable=False),
    sa.Column('sent_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('blocked_count', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cursor', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_broadcasts_created_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_broadcasts'))
    )
    op.create_index(op.f('ix_broadcasts_created_at'), 'broadcasts', ['created_at'], unique=False)
    op.create_table('coupons',
    sa.Column('id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('coupon_type', sa.Enum('PERCENTAGE', 'FIXED', name='coupontype', native_enum=False, length=16), nullable=False),
    sa.Column('value', sa.Numeric(precision=30, scale=8), nullable=False),
    sa.Column('currency', sa.String(length=16), nullable=False),
    sa.Column('max_discount', sa.Numeric(precision=30, scale=8), nullable=True),
    sa.Column('min_order_amount', sa.Numeric(precision=30, scale=8), nullable=False),
    sa.Column('max_redemptions', sa.Integer(), nullable=True),
    sa.Column('max_redemptions_per_user', sa.Integer(), nullable=False),
    sa.Column('redemptions_count', sa.Integer(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('product_ids', app.db.base.JSONB(), nullable=False),
    sa.Column('category_ids', app.db.base.JSONB(), nullable=False),
    sa.Column('reseller_only', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', app.db.base.GUID(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('max_redemptions IS NULL OR max_redemptions > 0', name=op.f('ck_coupons_max_redemptions_positive')),
    sa.CheckConstraint('value > 0', name=op.f('ck_coupons_value_positive')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_coupons_created_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_coupons')),
    sa.UniqueConstraint('code', name='uq_coupons_code')
    )
    op.create_index(op.f('ix_coupons_created_at'), 'coupons', ['created_at'], unique=False)
    op.create_index(op.f('ix_coupons_is_active'), 'coupons', ['is_active'], unique=False)
    op.create_table('notifications',
    sa.Column('id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('user_id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('kind', sa.Enum('PAYMENT', 'ORDER', 'DELIVERY', 'SUPPORT', 'REFERRAL', 'SYSTEM', 'RESTOCK', name='notificationkind', native_enum=False, length=16), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('payload', app.db.base.JSONB(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pushed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index('ix_notifications_user_read', 'notifications', ['user_id', 'read_at'], unique=False)
    op.create_table('payment_methods',
    sa.Column('id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('provider_id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('display_name', sa.String(length=64), nullable=False),
    sa.Column('emoji', sa.String(length=8), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('sort_priority', sa.Integer(), nullable=False),
    sa.Column('asset', sa.String(length=16), nullable=False),
    sa.Column('asset_decimals', sa.Integer(), nullable=False),
    sa.Column('network', sa.Enum('TRC20', 'BEP20', 'ERC20', 'TON', 'SOL', 'AVAXC', 'ARBITRUM', 'POLYGON', 'BTC', 'LTC', 'EXCHANGE_INTERNAL', name='networkcode', native_enum=False, length=24), nullable=False),
    sa.Column('network_label', sa.String(length=64), nullable=False),
    sa.Column('receiving_address', sa.String(length=255), nullable=True),
    sa.Column('token_contract', sa.String(length=128), nullable=True),
    sa.Column('requires_memo', sa.Boolean(), nullable=False),
    sa.Column('memo_template', sa.String(length=64), nullable=True),
    sa.Column('required_confirmations', sa.Integer(), nullable=False),
    sa.Column('payment_window_seconds', sa.Integer(), nullable=False),
    sa.Column('min_amount', sa.Numeric(precision=30, scale=8), nullable=True),
    sa.Column('max_amount', sa.Numeric(precision=30, scale=8), nullable=True),
    sa.Column('quote_rate', sa.Numeric(precision=30, scale=8), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('warning_text', sa.Text(), nullable=True),
    sa.Column('config', app.db.base.JSONB(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('asset_decimals >= 0', name=op.f('ck_payment_methods_decimals_non_negative')),
    sa.CheckConstraint('required_confirmations >= 0', name=op.f('ck_payment_methods_confirmations_non_negative')),
    sa.ForeignKeyConstraint(['provider_id'], ['payment_providers.id'], name=op.f('fk_payment_methods_provider_id_payment_providers'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment_methods')),
    sa.UniqueConstraint('code', name='uq_payment_methods_code')
    )
    op.create_index(op.f('ix_payment_methods_created_at'), 'payment_methods', ['created_at'], unique=False)
    op.create_index('ix_payment_methods_enabled', 'payment_methods', ['is_enabled', 'sort_priority'], unique=False)
    op.create_index(op.f('ix_payment_methods_provider_id'), 'payment_methods', ['provider_id'], unique=False)
    op.create_table('products',
    sa.Column('id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('sku', sa.String(length=64), nullable=False),
    sa.Column('category_id', app.db.base.GUID(length=36), nullable=True),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('name_bn', sa.String(length=160), nullable=True),
    sa.Column('short_description', sa.String(length=255), nullable=False),
    sa.Column('short_description_bn', sa.String(length=255), nullable=True),
    sa.Column('full_description', sa.Text(), nullable=False),
    sa.Column('full_description_bn', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=30, scale=8), nullable=False),
    sa.Column('currency', sa.String(length=16), nullable=False),
    sa.Column('compare_at_price', sa.Numeric(precision=30, scale=8), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'INACTIVE', 'HIDDEN', 'ARCHIVED', name='productstatus', native_enum=False, length=16), nullable=False),
    sa.Column('delivery_type', sa.Enum('STOCK_ITEM', 'STATIC_PAYLOAD', 'FILE', 'MANUAL', name='deliverytype', native_enum=False, length=16), nullable=False),
    sa.Column('delivery_payload', sa.Text(), nullable=True),
    sa.Column('delivery_file_id', sa.String(length=255), nullable=True),
    sa.Column('delivery_instructions', sa.Text(), nullable=True),
    sa.Column('min_quantity', sa.Integer(), nullable=False),
    sa.Column('max_quantity', sa.Integer(), nullable=True),
    sa.Column('stock_override', sa.Integer(), nullable=True),
    sa.Column('low_stock_threshold', sa.Integer(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('is_best_seller', sa.Boolean(), nullable=False),
    sa.Column('is_new_arrival', sa.Boolean(), nullable=False),
    sa.Column('sort_priority', sa.Integer(), nullable=False),
    sa.Column('available_to_customers', sa.Boolean(), nullable=False),
    sa.Column('available_to_resellers', sa.Boolean(), nullable=False),
    sa.Column('reseller_price', sa.Numeric(precision=30, scale=8), nullable=True),
    sa.Column('reseller_min_price', sa.Numeric(precision=30, scale=8), nullable=True),
    sa.Column('reseller_recommended_price', sa.Numeric(precision=30, scale=8), nullable=True),
    sa.Column('features', app.db.base.JSONB(), nullable=False),
    sa.Column('included_items', app.db.base.JSONB(), nullable=False),
    sa.Column('requirements', app.db.base.JSONB(), nullable=False),
    sa.Column('faq', app.db.base.JSONB(), nullable=False),
    sa.Column('product_metadata', app.db.base.JSONB(), nullable=False),
    sa.Column('sales_count', sa.Integer(), nullable=False),
    sa.Column('views_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('max_quantity IS NULL OR max_quantity >= min_quantity', name=op.f('ck_products_quantity_range')),
    sa.CheckConstraint('min_quantity >= 1', name=op.f('ck_products_min_quantity_positive')),
    sa.CheckConstraint('price >= 0', name=op.f('ck_products_price_non_negative')),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_products_category_id_categories'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products')),
    sa.UniqueConstraint('sku', name='uq_products_sku')
    )
    op.create_index(op.f('ix_products_available_to_resellers'), 'products', ['available_to_resellers'], unique=False)
    op.create_index(op.f('ix_products_category_id'), 'products', ['category_id'], unique=False)
    op.create_index(op.f('ix_products_created_at'), 'products', ['created_at'], unique=False)
    op.create_index(op.f('ix_products_is_best_seller'), 'products', ['is_best_seller'], unique=False)
    op.create_index(op.f('ix_products_is_featured'), 'products', ['is_featured'], unique=False)
    op.create_index(op.f('ix_products_is_new_arrival'), 'products', ['is_new_arrival'], unique=False)
    op.create_index('ix_products_listing', 'products', ['status', 'sort_priority', 'created_at'], unique=False)
    op.create_index(op.f('ix_products_status'), 'products', ['status'], unique=False)
    op.create_index('ix_products_status_category', 'products', ['status', 'category_id'], unique=False)
    op.create_table('reseller_accounts',
    sa.Column('id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('user_id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('business_name', sa.String(length=160), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'SUSPENDED', 'REVOKED', name='resellerstatus', native_enum=False, length=16), nullable=False),
    sa.Column('terms_accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('terms_version', sa.String(length=16), nullable=True),
    sa.Column('discount_percent', sa.Numeric(precision=30, scale=8), nullable=False),
    sa.Column('rate_limit_per_minute', sa.Integer(), nullable=False),
    sa.Column('ip_allowlist', app.db.base.JSONB(), nullable=False),
    sa.Column('api_requests_count', sa.Integer(), nullable=False),
    sa.Column('orders_count', sa.Integer(), nullable=False),
    sa.Column('sales_total', sa.Numeric(precision=30, scale=8), nullable=False),
    sa.Column('sales_currency', sa.String(length=16), nullable=False),
    sa.Column('suspended_reason', sa.String(length=255), nullable=True),
    sa.Column('suspended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('risk_flags', app.db.base.JSONB(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_reseller_accounts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reseller_accounts')),
    sa.UniqueConstraint('user_id', name='uq_reseller_accounts_user_id')
    )
    op.create_index(op.f('ix_reseller_accounts_created_at'), 'reseller_accounts', ['created_at'], unique=False)
    op.create_index(op.f('ix_reseller_accounts_status'), 'reseller_accounts', ['status'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name=op.f('fk_role_permissions_permission_id_permissions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_role_permissions_role_id_roles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id', name=op.f('pk_role_permissions'))
    )
    op.create_table('system_settings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=96), nullable=False),
    sa.Column('value', app.db.base.JSONB(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('updated_by_id', app.db.base.GUID(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_system_settings_updated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_system_settings')),
    sa.UniqueConstraint('key', name='uq_system_settings_key')
    )
    op.create_index(op.f('ix_system_settings_created_at'), 'system_settings', ['created_at'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('granted_by_id', app.db.base.GUID(length=36), nullable=True),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['granted_by_id'], ['users.id'], name=op.f('fk_user_roles_granted_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_user_roles_role_id_roles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_roles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id', name=op.f('pk_user_roles'))
    )
    op.create_table('api_keys',
    sa.Column('id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('reseller_id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('public_id', sa.String(length=16), nullable=False),
    sa.Column('prefix', sa.String(length=16), nullable=False),
    sa.Column('key_hash', sa.String(length=128), nullable=False),
    sa.Column('scopes', app.db.base.JSONB(), nullable=False),
    sa.Column('is_live', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_ip', sa.String(length=64), nullable=True),
    sa.Column('requests_count', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_by_id', app.db.base.GUID(length=36), nullable=True),
    sa.Column('rate_limit_per_minute', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reseller_id'], ['reseller_accounts.id'], name=op.f('fk_api_keys_reseller_id_reseller_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['revoked_by_id'], ['users.id'], name=op.f('fk_api_keys_revoked_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_keys')),
    sa.UniqueConstraint('key_hash', name='uq_api_keys_key_hash'),
    sa.UniqueConstraint('public_id', name='uq_api_keys_public_id')
    )
    op.create_index(op.f('ix_api_keys_created_at'), 'api_keys', ['created_at'], unique=False)
    op.create_index('ix_api_keys_reseller_active', 'api_keys', ['reseller_id', 'revoked_at'], unique=False)
    op.create_table('orders',
    sa.Column('id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('reference', sa.String(length=32), nullable=False),
    sa.Column('user_id', app.db.base.GUID(length=36), nullable=True),
    sa.Column('reseller_id', app.db.base.GUID(length=36), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('customer_reference', sa.String(length=128), nullable=True),
    sa.Column('reseller_reference', sa.String(length=128), nullable=True),
    sa.Column('status', sa.Enum('CREATED', 'PAYMENT_PENDING', 'PAYMENT_VERIFIED', 'FULFILLING', 'DELIVERED', 'COMPLETED', 'CANCELLED', 'EXPIRED', 'MANUAL_REVIEW', 'DELIVERY_FAILED', 'REFUNDED', name='orderstatus', native_enum=False, length=24), nullable=False),
    sa.Column('currency', sa.String(length=16), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=30, scale=8), nullable=False),
    sa.Column('discount_total', sa.Numeric(precision=30, scale=8), nullable=False),
    sa.Column('total', sa.Numeric(precision=30, scale=8), nullable=False),
    sa.Column('coupon_id', app.db.base.GUID(length=36), nullable=True),
    sa.Column('coupon_code', sa.String(length=32), nullable=True),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('order_metadata', app.db.base.JSONB(), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancellation_reason', sa.String(length=255), nullable=True),
    sa.Column('review_reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('discount_total >= 0', name=op.f('ck_orders_discount_non_negative')),
    sa.CheckConstraint('subtotal >= 0', name=op.f('ck_orders_subtotal_non_negative')),
    sa.CheckConstraint('total >= 0', name=op.f('ck_orders_total_non_negative')),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupons.id'], name=op.f('fk_orders_coupon_id_coupons'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reseller_id'], ['reseller_accounts.id'], name=op.f('fk_orders_reseller_id_reseller_accounts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_orders_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders')),
    sa.UniqueConstraint('reference', name='uq_orders_reference'),
    sa.UniqueConstraint('reseller_id', 'idempotency_key', name='uq_orders_idempotency_key')
    )
    op.create_index(op.f('ix_orders_correlation_id'), 'orders', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_orders_created_at'), 'orders', ['created_at'], unique=False)
    op.create_index(op.f('ix_orders_reseller_id'), 'orders', ['reseller_id'], unique=False)
    op.create_index('ix_orders_status_created', 'orders', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.create_index('ix_orders_user_status', 'orders', ['user_id', 'status'], unique=False)
    op.create_table('product_media',
    sa.Column('id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('product_id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('file_id', sa.String(length=255), nullable=True),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('media_type', sa.String(length=16), nullable=False),
    sa.Column('caption', sa.String(length=255), nullable=True),
    sa.Column('sort_priority', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_media_product_id_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_media'))
    )
    op.create_index(op.f('ix_product_media_created_at'), 'product_media', ['created_at'], unique=False)
    op.create_index(op.f('ix_product_media_product_id'), 'product_media', ['product_id'], unique=False)
    op.create_table('restock_subscriptions',
    sa.Column('id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('user_id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('product_id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_restock_subscriptions_product_id_products'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_restock_subscriptions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_restock_subscriptions')),
    sa.UniqueConstraint('user_id', 'product_id', name='uq_restock_subscriptions_user_id')
    )
    op.create_index(op.f('ix_restock_subscriptions_created_at'), 'restock_subscriptions', ['created_at'], unique=False)
    op.create_index(op.f('ix_restock_subscriptions_product_id'), 'restock_subscriptions', ['product_id'], unique=False)
    op.create_table('webhook_endpoints',
    sa.Column('id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('reseller_id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('encrypted_secret', sa.Text(), nullable=False),
    sa.Column('secret_hint', sa.String(length=24), nullable=False),
    sa.Column('events', app.db.base.JSONB(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('disabled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_failure_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_status_code', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reseller_id'], ['reseller_accounts.id'], name=op.f('fk_webhook_endpoints_reseller_id_reseller_accounts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_webhook_endpoints'))
    )
    op.create_index(op.f('ix_webhook_endpoints_created_at'), 'webhook_endpoints', ['created_at'], unique=False)
    op.create_index('ix_webhook_endpoints_reseller', 'webhook_endpoints', ['reseller_id', 'is_active'], unique=False)
    op.create_table('coupon_usage',
    sa.Column('id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('coupon_id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('user_id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('order_id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=30, scale=8), nullable=False),
    sa.Column('reverted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupons.id'], name=op.f('fk_coupon_usage_coupon_id_coupons'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_coupon_usage_order_id_orders'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_coupon_usage_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_coupon_usage')),
    sa.UniqueConstraint('order_id', name='uq_coupon_usage_order_id')
    )
    op.create_index('ix_coupon_usage_coupon_user', 'coupon_usage', ['coupon_id', 'user_id'], unique=False)
    op.create_index(op.f('ix_coupon_usage_created_at'), 'coupon_usage', ['created_at'], unique=False)
    op.create_table('order_items',
    sa.Column('id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('order_id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('product_id', app.db.base.GUID(length=36), nullable=True),
    sa.Column('product_name', sa.String(length=160), nullable=False),
    sa.Column('product_sku', sa.String(length=64), nullable=False),
    sa.Column('delivery_type', sa.String(length=24), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=30, scale=8), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=30, scale=8), nullable=False),
    sa.Column('currency', sa.String(length=16), nullable=False),
    sa.Column('product_snapshot', app.db.base.JSONB(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_order_items_quantity_positive')),
    sa.CheckConstraint('unit_price >= 0', name=op.f('ck_order_items_unit_price_non_negative')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_order_items_order_id_orders'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_order_items_product_id_products'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_items'))
    )
    op.create_index(op.f('ix_order_items_created_at'), 'order_items', ['created_at'], unique=False)
    op.create_index('ix_order_items_order', 'order_items', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_items_product_id'), 'order_items', ['product_id'], unique=False)
    op.create_table('payment_intents',
    sa.Column('id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('reference', sa.String(length=32), nullable=False),
    sa.Column('order_id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('payment_method_id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('provider_code', sa.Enum('BINANCE', 'BINANCE_PAY', 'BYBIT', 'OKX', 'TRON', 'EVM', 'TON', 'SOLANA', 'UTXO', name='providercode', native_enum=False, length=24), nullable=False),
    sa.Column('network', sa.Enum('TRC20', 'BEP20', 'ERC20', 'TON', 'SOL', 'AVAXC', 'ARBITRUM', 'POLYGON', 'BTC', 'LTC', 'EXCHANGE_INTERNAL', name='networkcode', native_enum=False, length=24), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'AWAITING_PAYMENT', 'SUBMITTED', 'DETECTING', 'DETECTED', 'VERIFYING', 'PENDING_CONFIRMATION', 'VERIFIED', 'UNDER_REVIEW', 'FAILED', 'EXPIRED', 'CANCELLED', name='paymentstatus', native_enum=False, length=24), nullable=False),
    sa.Column('order_amount', sa.Numeric(precision=30, scale=8), nullable=False),
    sa.Column('order_currency', sa.String(length=16), nullable=False),
    sa.Column('expected_amount', sa.Numeric(precision=30, scale=8), nullable=False),
    sa.Column('expected_amount_units', sa.Numeric(precision=78, scale=0, asdecimal=False), nullable=False),
    sa.Column('asset', sa.String(length=16), nullable=False),
    sa.Column('asset_decimals', sa.Integer(), nullable=False),
    sa.Column('destination', sa.String(length=255), nullable=False),
    sa.Column('destination_normalized', sa.String(length=255), nullable=False),
    sa.Column('token_contract', sa.String(length=128), nullable=True),
    sa.Column('memo', sa.String(length=64), nullable=True),
    sa.Column('required_confirmations', sa.Integer(), nullable=False),
    sa.Column('quote_rate', sa.Numeric(precision=30, scale=8), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('received_amount', sa.Numeric(precision=30, scale=8), nullable=True),
    sa.Column('received_amount_units', sa.Numeric(precision=78, scale=0, asdecimal=False), nullable=True),
    sa.Column('confirmations', sa.Integer(), nullable=False),
    sa.Column('verification_attempts', sa.Integer(), nullable=False),
    sa.Column('next_poll_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_outcome', sa.Enum('VERIFIED', 'NOT_FOUND', 'PENDING_CONFIRMATION', 'UNDERPAID', 'OVERPAID', 'WRONG_NETWORK', 'WRONG_ASSET', 'WRONG_RECEIVER', 'DUPLICATE', 'FAILED_TRANSACTION', 'OUTSIDE_WINDOW', 'PROVIDER_ERROR', 'UNSUPPORTED', 'MEMO_MISMATCH', name='verificationoutcome', native_enum=False, length=32), nullable=True),
    sa.Column('failure_reason', sa.String(length=255), nullable=True),
    sa.Column('review_reason', sa.String(length=255), nullable=True),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('verification_config', app.db.base.JSONB(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('expected_amount > 0', name=op.f('ck_payment_intents_expected_amount_positive')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_payment_intents_order_id_orders'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['payment_method_id'], ['payment_methods.id'], name=op.f('fk_payment_intents_payment_method_id_payment_methods'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment_intents')),
    sa.UniqueConstraint('reference', name='uq_payment_intents_reference')
    )
    op.create_index(op.f('ix_payment_intents_correlation_id'), 'payment_intents', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_payment_intents_created_at'), 'payment_intents', ['created_at'], unique=False)
    op.create_index(op.f('ix_payment_intents_destination_normalized'), 'payment_intents', ['destination_normalized'], unique=False)
    op.create_index('ix_payment_intents_order', 'payment_intents', ['order_id'], unique=False)
    op.create_index('ix_payment_intents_polling', 'payment_intents', ['status', 'next_poll_at'], unique=False)
    op.create_index('ix_payment_intents_status_expires', 'payment_intents', ['status', 'expires_at'], unique=False)
    op.create_table('referrals',
    sa.Column('id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('referrer_id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('referred_user_id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'QUALIFIED', 'REWARDED', 'REJECTED', name='referralstatus', native_enum=False, length=16), nullable=False),
    sa.Column('qualifying_order_id', app.db.base.GUID(length=36), nullable=True),
    sa.Column('reward_amount', sa.Numeric(precision=30, scale=8), nullable=False),
    sa.Column('reward_currency', sa.String(length=16), nullable=False),
    sa.Column('rewarded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('signals', app.db.base.JSONB(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['qualifying_order_id'], ['orders.id'], name=op.f('fk_referrals_qualifying_order_id_orders'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['referred_user_id'], ['users.id'], name=op.f('fk_referrals_referred_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['referrer_id'], ['users.id'], name=op.f('fk_referrals_referrer_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_referrals')),
    sa.UniqueConstraint('referred_user_id', name='uq_referrals_referred_user_id')
    )
    op.create_index(op.f('ix_referrals_created_at'), 'referrals', ['created_at'], unique=False)
    op.create_index('ix_referrals_referrer_status', 'referrals', ['referrer_id', 'status'], unique=False)
    op.create_table('support_tickets',
    sa.Column('id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('reference', sa.String(length=24), nullable=False),
    sa.Column('user_id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('category', sa.Enum('PAYMENT', 'ORDER', 'PRODUCT', 'TECHNICAL', 'OTHER', name='ticketcategory', native_enum=False, length=16), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'NORMAL', 'HIGH', 'URGENT', name='ticketpriority', native_enum=False, length=16), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'ASSIGNED', 'WAITING_USER', 'RESOLVED', 'CLOSED', name='ticketstatus', native_enum=False, length=16), nullable=False),
    sa.Column('subject', sa.String(length=160), nullable=False),
    sa.Column('order_id', app.db.base.GUID(length=36), nullable=True),
    sa.Column('assigned_to_id', app.db.base.GUID(length=36), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('internal_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], name=op.f('fk_support_tickets_assigned_to_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_support_tickets_order_id_orders'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_support_tickets_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_support_tickets')),
    sa.UniqueConstraint('reference', name='uq_support_tickets_reference')
    )
    op.create_index(op.f('ix_support_tickets_assigned_to_id'), 'support_tickets', ['assigned_to_id'], unique=False)
    op.create_index(op.f('ix_support_tickets_created_at'), 'support_tickets', ['created_at'], unique=False)
    op.create_index(op.f('ix_support_tickets_last_message_at'), 'support_tickets', ['last_message_at'], unique=False)
    op.create_index('ix_support_tickets_status_priority', 'support_tickets', ['status', 'priority'], unique=False)
    op.create_index('ix_support_tickets_user', 'support_tickets', ['user_id', 'status'], unique=False)
    op.create_table('webhook_deliveries',
    sa.Column('id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('endpoint_id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('event_id', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=48), nullable=False),
    sa.Column('order_id', app.db.base.GUID(length=36), nullable=True),
    sa.Column('payload', app.db.base.JSONB(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'DELIVERED', 'FAILED', 'EXHAUSTED', name='webhookdeliverystatus', native_enum=False, length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_status_code', sa.Integer(), nullable=True),
    sa.Column('last_error', sa.String(length=512), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['endpoint_id'], ['webhook_endpoints.id'], name=op.f('fk_webhook_deliveries_endpoint_id_webhook_endpoints'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_webhook_deliveries_order_id_orders'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_webhook_deliveries')),
    sa.UniqueConstraint('endpoint_id', 'event_id', name='uq_webhook_deliveries_endpoint_id')
    )
    op.create_index(op.f('ix_webhook_deliveries_created_at'), 'webhook_deliveries', ['created_at'], unique=False)
    op.create_index(op.f('ix_webhook_deliveries_order_id'), 'webhook_deliveries', ['order_id'], unique=False)
    op.create_index('ix_webhook_deliveries_pending', 'webhook_deliveries', ['status', 'next_attempt_at'], unique=False)
    op.create_table('deliveries',
    sa.Column('id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('order_id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('order_item_id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'CANCELLED', name='deliverystatus', native_enum=False, length=16), nullable=False),
    sa.Column('delivery_type', sa.String(length=24), nullable=False),
    sa.Column('encrypted_payload', sa.Text(), nullable=True),
    sa.Column('file_id', sa.String(length=255), nullable=True),
    sa.Column('inventory_item_ids', app.db.base.JSONB(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.String(length=512), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_viewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_deliveries_order_id_orders'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], name=op.f('fk_deliveries_order_item_id_order_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deliveries')),
    sa.UniqueConstraint('order_item_id', name='uq_deliveries_order_item_id')
    )
    op.create_index(op.f('ix_deliveries_created_at'), 'deliveries', ['created_at'], unique=False)
    op.create_index(op.f('ix_deliveries_order_id'), 'deliveries', ['order_id'], unique=False)
    op.create_index('ix_deliveries_status_next_attempt', 'deliveries', ['status', 'next_attempt_at'], unique=False)
    op.create_table('inventory',
    sa.Column('id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('product_id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'RESERVED', 'SOLD', 'INVALID', name='stockitemstatus', native_enum=False, length=16), nullable=False),
    sa.Column('secret_payload', sa.Text(), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('preview', sa.String(length=64), nullable=False),
    sa.Column('order_item_id', app.db.base.GUID(length=36), nullable=True),
    sa.Column('sold_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('added_by_id', app.db.base.GUID(length=36), nullable=True),
    sa.Column('item_metadata', app.db.base.JSONB(), nullable=False),
    sa.Column('invalid_reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['added_by_id'], ['users.id'], name=op.f('fk_inventory_added_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], name=op.f('fk_inventory_order_item_id_order_items'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_inventory_product_id_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory')),
    sa.UniqueConstraint('product_id', 'fingerprint', name='uq_inventory_product_id')
    )
    op.create_index(op.f('ix_inventory_created_at'), 'inventory', ['created_at'], unique=False)
    op.create_index(op.f('ix_inventory_order_item_id'), 'inventory', ['order_item_id'], unique=False)
    op.create_index('ix_inventory_product_status', 'inventory', ['product_id', 'status'], unique=False)
    op.create_table('ledger_entries',
    sa.Column('id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('entry_type', sa.Enum('ORDER_CREATED', 'PAYMENT_VERIFIED', 'PAYMENT_OVERPAID', 'PAYMENT_UNDERPAID', 'REFUND', 'MANUAL_ADJUSTMENT', 'REFERRAL_REWARD', name='ledgerentrytype', native_enum=False, length=32), nullable=False),
    sa.Column('amount', sa.Numeric(precision=30, scale=8), nullable=False),
    sa.Column('currency', sa.String(length=16), nullable=False),
    sa.Column('order_id', app.db.base.GUID(length=36), nullable=True),
    sa.Column('payment_intent_id', app.db.base.GUID(length=36), nullable=True),
    sa.Column('user_id', app.db.base.GUID(length=36), nullable=True),
    sa.Column('actor_id', app.db.base.GUID(length=36), nullable=True),
    sa.Column('dedupe_key', sa.String(length=160), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('details', app.db.base.JSONB(), nullable=False),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_ledger_entries_actor_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_ledger_entries_order_id_orders'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['payment_intent_id'], ['payment_intents.id'], name=op.f('fk_ledger_entries_payment_intent_id_payment_intents'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ledger_entries_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ledger_entries')),
    sa.UniqueConstraint('dedupe_key', name='uq_ledger_entries_dedupe_key')
    )
    op.create_index(op.f('ix_ledger_entries_created_at'), 'ledger_entries', ['created_at'], unique=False)
    op.create_index('ix_ledger_entries_order', 'ledger_entries', ['order_id'], unique=False)
    op.create_index('ix_ledger_entries_type_created', 'ledger_entries', ['entry_type', 'created_at'], unique=False)
    op.create_table('payment_attempts',
    sa.Column('id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('payment_intent_id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('provider_code', sa.Enum('BINANCE', 'BINANCE_PAY', 'BYBIT', 'OKX', 'TRON', 'EVM', 'TON', 'SOLANA', 'UTXO', name='providercode', native_enum=False, length=24), nullable=False),
    sa.Column('network', sa.Enum('TRC20', 'BEP20', 'ERC20', 'TON', 'SOL', 'AVAXC', 'ARBITRUM', 'POLYGON', 'BTC', 'LTC', 'EXCHANGE_INTERNAL', name='networkcode', native_enum=False, length=24), nullable=False),
    sa.Column('submitted_reference', sa.String(length=160), nullable=True),
    sa.Column('submitted_txid', sa.String(length=160), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verification_count', sa.Integer(), nullable=False),
    sa.Column('last_outcome', sa.Enum('VERIFIED', 'NOT_FOUND', 'PENDING_CONFIRMATION', 'UNDERPAID', 'OVERPAID', 'WRONG_NETWORK', 'WRONG_ASSET', 'WRONG_RECEIVER', 'DUPLICATE', 'FAILED_TRANSACTION', 'OUTSIDE_WINDOW', 'PROVIDER_ERROR', 'UNSUPPORTED', 'MEMO_MISMATCH', name='verificationoutcome', native_enum=False, length=32), nullable=True),
    sa.Column('failure_reason', sa.String(length=255), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['payment_intent_id'], ['payment_intents.id'], name=op.f('fk_payment_attempts_payment_intent_id_payment_intents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment_attempts'))
    )
    op.create_index(op.f('ix_payment_attempts_created_at'), 'payment_attempts', ['created_at'], unique=False)
    op.create_index('ix_payment_attempts_intent', 'payment_attempts', ['payment_intent_id'], unique=False)
    op.create_index('ix_payment_attempts_reference', 'payment_attempts', ['submitted_reference'], unique=False)
    op.create_table('payment_consumptions',
    sa.Column('id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('payment_intent_id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('order_id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('provider_code', sa.Enum('BINANCE', 'BINANCE_PAY', 'BYBIT', 'OKX', 'TRON', 'EVM', 'TON', 'SOLANA', 'UTXO', name='providercode', native_enum=False, length=24), nullable=False),
    sa.Column('network', sa.Enum('TRC20', 'BEP20', 'ERC20', 'TON', 'SOL', 'AVAXC', 'ARBITRUM', 'POLYGON', 'BTC', 'LTC', 'EXCHANGE_INTERNAL', name='networkcode', native_enum=False, length=24), nullable=False),
    sa.Column('external_id', sa.String(length=160), nullable=False),
    sa.Column('amount', sa.Numeric(precision=30, scale=8), nullable=False),
    sa.Column('amount_units', sa.Numeric(precision=78, scale=0, asdecimal=False), nullable=False),
    sa.Column('asset', sa.String(length=16), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_payment_consumptions_order_id_orders'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['payment_intent_id'], ['payment_intents.id'], name=op.f('fk_payment_consumptions_payment_intent_id_payment_intents'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment_consumptions')),
    sa.UniqueConstraint('fingerprint', name='uq_payment_consumptions_fingerprint'),
    sa.UniqueConstraint('payment_intent_id', name='uq_payment_consumptions_payment_intent_id')
    )
    op.create_index(op.f('ix_payment_consumptions_created_at'), 'payment_consumptions', ['created_at'], unique=False)
    op.create_index(op.f('ix_payment_consumptions_order_id'), 'payment_consumptions', ['order_id'], unique=False)
    op.create_table('reconciliation_records',
    sa.Column('id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('kind', sa.Enum('UNMATCHED_TRANSACTION', 'DUPLICATE_TRANSACTION', 'LATE_PAYMENT', 'WRONG_NETWORK', 'AMOUNT_MISMATCH', 'EXPIRED_WITH_FUNDS', 'PROVIDER_INCONSISTENCY', 'STUCK_DELIVERY', 'ORPHAN_PAYMENT', name='reconciliationkind', native_enum=False, length=32), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'INVESTIGATING', 'RESOLVED', 'IGNORED', name='reconciliationstatus', native_enum=False, length=16), nullable=False),
    sa.Column('dedupe_key', sa.String(length=200), nullable=False),
    sa.Column('summary', sa.String(length=255), nullable=False),
    sa.Column('payment_intent_id', app.db.base.GUID(length=36), nullable=True),
    sa.Column('order_id', app.db.base.GUID(length=36), nullable=True),
    sa.Column('details', app.db.base.JSONB(), nullable=False),
    sa.Column('resolved_by_id', app.db.base.GUID(length=36), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_note', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_reconciliation_records_order_id_orders'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['payment_intent_id'], ['payment_intents.id'], name=op.f('fk_reconciliation_records_payment_intent_id_payment_intents'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resolved_by_id'], ['users.id'], name=op.f('fk_reconciliation_records_resolved_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reconciliation_records')),
    sa.UniqueConstraint('dedupe_key', name='uq_reconciliation_records_dedupe_key')
    )
    op.create_index(op.f('ix_reconciliation_records_created_at'), 'reconciliation_records', ['created_at'], unique=False)
    op.create_index('ix_reconciliation_records_status_kind', 'reconciliation_records', ['status', 'kind'], unique=False)
    op.create_table('refunds',
    sa.Column('id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('order_id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('payment_intent_id', app.db.base.GUID(length=36), nullable=True),
    sa.Column('amount', sa.Numeric(precision=30, scale=8), nullable=False),
    sa.Column('currency', sa.String(length=16), nullable=False),
    sa.Column('status', sa.Enum('REQUESTED', 'APPROVED', 'PROCESSING', 'COMPLETED', 'REJECTED', 'FAILED', name='refundstatus', native_enum=False, length=16), nullable=False),
    sa.Column('reason', sa.String(length=512), nullable=False),
    sa.Column('destination', sa.String(length=255), nullable=True),
    sa.Column('destination_network', sa.String(length=32), nullable=True),
    sa.Column('external_reference', sa.String(length=255), nullable=True),
    sa.Column('requested_by_id', app.db.base.GUID(length=36), nullable=True),
    sa.Column('approved_by_id', app.db.base.GUID(length=36), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name=op.f('ck_refunds_amount_positive')),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], name=op.f('fk_refunds_approved_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_refunds_order_id_orders'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['payment_intent_id'], ['payment_intents.id'], name=op.f('fk_refunds_payment_intent_id_payment_intents'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], name=op.f('fk_refunds_requested_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refunds'))
    )
    op.create_index(op.f('ix_refunds_created_at'), 'refunds', ['created_at'], unique=False)
    op.create_index('ix_refunds_order', 'refunds', ['order_id'], unique=False)
    op.create_table('support_messages',
    sa.Column('id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('ticket_id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('author_id', app.db.base.GUID(length=36), nullable=True),
    sa.Column('is_staff', sa.Boolean(), nullable=False),
    sa.Column('is_internal', sa.Boolean(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('attachment_file_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_support_messages_author_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ticket_id'], ['support_tickets.id'], name=op.f('fk_support_messages_ticket_id_support_tickets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_support_messages'))
    )
    op.create_index(op.f('ix_support_messages_created_at'), 'support_messages', ['created_at'], unique=False)
    op.create_index('ix_support_messages_ticket', 'support_messages', ['ticket_id', 'created_at'], unique=False)
    op.create_table('inventory_adjustments',
    sa.Column('id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('product_id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('inventory_item_id', app.db.base.GUID(length=36), nullable=True),
    sa.Column('actor_id', app.db.base.GUID(length=36), nullable=True),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('details', app.db.base.JSONB(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_inventory_adjustments_actor_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory.id'], name=op.f('fk_inventory_adjustments_inventory_item_id_inventory'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_inventory_adjustments_product_id_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory_adjustments'))
    )
    op.create_index(op.f('ix_inventory_adjustments_created_at'), 'inventory_adjustments', ['created_at'], unique=False)
    op.create_index(op.f('ix_inventory_adjustments_product_id'), 'inventory_adjustments', ['product_id'], unique=False)
    op.create_table('inventory_reservations',
    sa.Column('id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('inventory_item_id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('order_id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('order_item_id', app.db.base.GUID(length=36), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'CONSUMED', 'RELEASED', 'EXPIRED', name='reservationstatus', native_enum=False, length=16), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory.id'], name=op.f('fk_inventory_reservations_inventory_item_id_inventory'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_inventory_reservations_order_id_orders'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], name=op.f('fk_inventory_reservations_order_item_id_order_items'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory_reservations')),
    sa.UniqueConstraint('inventory_item_id', 'status', name='uq_inventory_reservations_inventory_item_id')
    )
    op.create_index(op.f('ix_inventory_reservations_created_at'), 'inventory_reservations', ['created_at'], unique=False)
    op.create_index('ix_inventory_reservations_expiry', 'inventory_reservations', ['status', 'expires_at'], unique=False)
    op.create_index('ix_inventory_reservations_order', 'inventory_reservations', ['order_id'], unique=False)
    op.create_table('verification_attempts',
    sa.Column('id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('payment_intent_id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('payment_attempt_id', app.db.base.GUID(length=36), nullable=True),
    sa.Column('provider_code', sa.Enum('BINANCE', 'BINANCE_PAY', 'BYBIT', 'OKX', 'TRON', 'EVM', 'TON', 'SOLANA', 'UTXO', name='providercode', native_enum=False, length=24), nullable=False),
    sa.Column('outcome', sa.Enum('VERIFIED', 'NOT_FOUND', 'PENDING_CONFIRMATION', 'UNDERPAID', 'OVERPAID', 'WRONG_NETWORK', 'WRONG_ASSET', 'WRONG_RECEIVER', 'DUPLICATE', 'FAILED_TRANSACTION', 'OUTSIDE_WINDOW', 'PROVIDER_ERROR', 'UNSUPPORTED', 'MEMO_MISMATCH', name='verificationoutcome', native_enum=False, length=32), nullable=False),
    sa.Column('checks', app.db.base.JSONB(), nullable=False),
    sa.Column('observed_amount', sa.Numeric(precision=30, scale=8), nullable=True),
    sa.Column('observed_confirmations', sa.Integer(), nullable=True),
    sa.Column('external_reference', sa.String(length=160), nullable=True),
    sa.Column('detail', sa.String(length=512), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['payment_attempt_id'], ['payment_attempts.id'], name=op.f('fk_verification_attempts_payment_attempt_id_payment_attempts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['payment_intent_id'], ['payment_intents.id'], name=op.f('fk_verification_attempts_payment_intent_id_payment_intents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_verification_attempts'))
    )
    op.create_index(op.f('ix_verification_attempts_created_at'), 'verification_attempts', ['created_at'], unique=False)
    op.create_index('ix_verification_attempts_intent_created', 'verification_attempts', ['payment_intent_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_verification_attempts_intent_created', table_name='verification_attempts')
    op.drop_index(op.f('ix_verification_attempts_created_at'), table_name='verification_attempts')
    op.drop_table('verification_attempts')
    op.drop_index('ix_inventory_reservations_order', table_name='inventory_reservations')
    op.drop_index('ix_inventory_reservations_expiry', table_name='inventory_reservations')
    op.drop_index(op.f('ix_inventory_reservations_created_at'), table_name='inventory_reservations')
    op.drop_table('inventory_reservations')
    op.drop_index(op.f('ix_inventory_adjustments_product_id'), table_name='inventory_adjustments')
    op.drop_index(op.f('ix_inventory_adjustments_created_at'), table_name='inventory_adjustments')
    op.drop_table('inventory_adjustments')
    op.drop_index('ix_support_messages_ticket', table_name='support_messages')
    op.drop_index(op.f('ix_support_messages_created_at'), table_name='support_messages')
    op.drop_table('support_messages')
    op.drop_index('ix_refunds_order', table_name='refunds')
    op.drop_index(op.f('ix_refunds_created_at'), table_name='refunds')
    op.drop_table('refunds')
    op.drop_index('ix_reconciliation_records_status_kind', table_name='reconciliation_records')
    op.drop_index(op.f('ix_reconciliation_records_created_at'), table_name='reconciliation_records')
    op.drop_table('reconciliation_records')
    op.drop_index(op.f('ix_payment_consumptions_order_id'), table_name='payment_consumptions')
    op.drop_index(op.f('ix_payment_consumptions_created_at'), table_name='payment_consumptions')
    op.drop_table('payment_consumptions')
    op.drop_index('ix_payment_attempts_reference', table_name='payment_attempts')
    op.drop_index('ix_payment_attempts_intent', table_name='payment_attempts')
    op.drop_index(op.f('ix_payment_attempts_created_at'), table_name='payment_attempts')
    op.drop_table('payment_attempts')
    op.drop_index('ix_ledger_entries_type_created', table_name='ledger_entries')
    op.drop_index('ix_ledger_entries_order', table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_created_at'), table_name='ledger_entries')
    op.drop_table('ledger_entries')
    op.drop_index('ix_inventory_product_status', table_name='inventory')
    op.drop_index(op.f('ix_inventory_order_item_id'), table_name='inventory')
    op.drop_index(op.f('ix_inventory_created_at'), table_name='inventory')
    op.drop_table('inventory')
    op.drop_index('ix_deliveries_status_next_attempt', table_name='deliveries')
    op.drop_index(op.f('ix_deliveries_order_id'), table_name='deliveries')
    op.drop_index(op.f('ix_deliveries_created_at'), table_name='deliveries')
    op.drop_table('deliveries')
    op.drop_index('ix_webhook_deliveries_pending', table_name='webhook_deliveries')
    op.drop_index(op.f('ix_webhook_deliveries_order_id'), table_name='webhook_deliveries')
    op.drop_index(op.f('ix_webhook_deliveries_created_at'), table_name='webhook_deliveries')
    op.drop_table('webhook_deliveries')
    op.drop_index('ix_support_tickets_user', table_name='support_tickets')
    op.drop_index('ix_support_tickets_status_priority', table_name='support_tickets')
    op.drop_index(op.f('ix_support_tickets_last_message_at'), table_name='support_tickets')
    op.drop_index(op.f('ix_support_tickets_created_at'), table_name='support_tickets')
    op.drop_index(op.f('ix_support_tickets_assigned_to_id'), table_name='support_tickets')
    op.drop_table('support_tickets')
    op.drop_index('ix_referrals_referrer_status', table_name='referrals')
    op.drop_index(op.f('ix_referrals_created_at'), table_name='referrals')
    op.drop_table('referrals')
    op.drop_index('ix_payment_intents_status_expires', table_name='payment_intents')
    op.drop_index('ix_payment_intents_polling', table_name='payment_intents')
    op.drop_index('ix_payment_intents_order', table_name='payment_intents')
    op.drop_index(op.f('ix_payment_intents_destination_normalized'), table_name='payment_intents')
    op.drop_index(op.f('ix_payment_intents_created_at'), table_name='payment_intents')
    op.drop_index(op.f('ix_payment_intents_correlation_id'), table_name='payment_intents')
    op.drop_table('payment_intents')
    op.drop_index(op.f('ix_order_items_product_id'), table_name='order_items')
    op.drop_index('ix_order_items_order', table_name='order_items')
    op.drop_index(op.f('ix_order_items_created_at'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_coupon_usage_created_at'), table_name='coupon_usage')
    op.drop_index('ix_coupon_usage_coupon_user', table_name='coupon_usage')
    op.drop_table('coupon_usage')
    op.drop_index('ix_webhook_endpoints_reseller', table_name='webhook_endpoints')
    op.drop_index(op.f('ix_webhook_endpoints_created_at'), table_name='webhook_endpoints')
    op.drop_table('webhook_endpoints')
    op.drop_index(op.f('ix_restock_subscriptions_product_id'), table_name='restock_subscriptions')
    op.drop_index(op.f('ix_restock_subscriptions_created_at'), table_name='restock_subscriptions')
    op.drop_table('restock_subscriptions')
    op.drop_index(op.f('ix_product_media_product_id'), table_name='product_media')
    op.drop_index(op.f('ix_product_media_created_at'), table_name='product_media')
    op.drop_table('product_media')
    op.drop_index('ix_orders_user_status', table_name='orders')
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_index('ix_orders_status_created', table_name='orders')
    op.drop_index(op.f('ix_orders_reseller_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_created_at'), table_name='orders')
    op.drop_index(op.f('ix_orders_correlation_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index('ix_api_keys_reseller_active', table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_created_at'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_system_settings_created_at'), table_name='system_settings')
    op.drop_table('system_settings')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_reseller_accounts_status'), table_name='reseller_accounts')
    op.drop_index(op.f('ix_reseller_accounts_created_at'), table_name='reseller_accounts')
    op.drop_table('reseller_accounts')
    op.drop_index('ix_products_status_category', table_name='products')
    op.drop_index(op.f('ix_products_status'), table_name='products')
    op.drop_index('ix_products_listing', table_name='products')
    op.drop_index(op.f('ix_products_is_new_arrival'), table_name='products')
    op.drop_index(op.f('ix_products_is_featured'), table_name='products')
    op.drop_index(op.f('ix_products_is_best_seller'), table_name='products')
    op.drop_index(op.f('ix_products_created_at'), table_name='products')
    op.drop_index(op.f('ix_products_category_id'), table_name='products')
    op.drop_index(op.f('ix_products_available_to_resellers'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_payment_methods_provider_id'), table_name='payment_methods')
    op.drop_index('ix_payment_methods_enabled', table_name='payment_methods')
    op.drop_index(op.f('ix_payment_methods_created_at'), table_name='payment_methods')
    op.drop_table('payment_methods')
    op.drop_index('ix_notifications_user_read', table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_coupons_is_active'), table_name='coupons')
    op.drop_index(op.f('ix_coupons_created_at'), table_name='coupons')
    op.drop_table('coupons')
    op.drop_index(op.f('ix_broadcasts_created_at'), table_name='broadcasts')
    op.drop_table('broadcasts')
    op.drop_index('ix_audit_logs_target', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_actor_created', table_name='audit_logs')
    op.drop_index('ix_audit_logs_action_created', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_users_username_lower', table_name='users')
    op.drop_index('ix_users_telegram_id', table_name='users')
    op.drop_index(op.f('ix_users_status'), table_name='users')
    op.drop_index(op.f('ix_users_referred_by_id'), table_name='users')
    op.drop_index(op.f('ix_users_last_seen_at'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_roles_created_at'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_provider_transactions_txid'), table_name='provider_transactions')
    op.drop_index(op.f('ix_provider_transactions_reference'), table_name='provider_transactions')
    op.drop_index('ix_provider_transactions_lookup', table_name='provider_transactions')
    op.drop_index(op.f('ix_provider_transactions_created_at'), table_name='provider_transactions')
    op.drop_table('provider_transactions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_payment_providers_is_enabled'), table_name='payment_providers')
    op.drop_index(op.f('ix_payment_providers_created_at'), table_name='payment_providers')
    op.drop_table('payment_providers')
    op.drop_index(op.f('ix_idempotency_records_expires_at'), table_name='idempotency_records')
    op.drop_index(op.f('ix_idempotency_records_created_at'), table_name='idempotency_records')
    op.drop_table('idempotency_records')
    op.drop_index(op.f('ix_categories_is_active'), table_name='categories')
    op.drop_index(op.f('ix_categories_created_at'), table_name='categories')
    op.drop_table('categories')
    op.drop_index('ix_blockchain_transactions_receiver', table_name='blockchain_transactions')
    op.drop_index(op.f('ix_blockchain_transactions_created_at'), table_name='blockchain_transactions')
    op.drop_table('blockchain_transactions')
    # ### end Alembic commands ###
