"""payment method quote rate timestamp

Revision ID: ac541d1dd891
Revises: a0bcf6dd96f1
Create Date: 2026-09-05 08:34:31.372053
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# Custom column types (GUID, JSONB, Money) live in the application's declarative
# base, so migrations import it rather than duplicating the definitions.
import app.db.base


revision: str = 'ac541d1dd891'
down_revision: str | None = 'a0bcf6dd96f1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_methods', sa.Column('quote_rate_updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment_methods', 'quote_rate_updated_at')
    # ### end Alembic commands ###
